inherits = "catppuccin_mocha"

"ui.background" = { bg = "sigma_blue", fg = "sigma_green" }
"ui.help" = { bg = "sigma_blue2", fg = "sigma_green" }
"ui.popup" = { bg = "sigma_blue2", fg = "sigma_green" }
"ui.info" = "sigma_green"
"ui.linenr" = "sigma_green2"
"ui.linenr.selected" = { fg = "sigma_green", modifiers = ["bold"] }
"ui.menu" = { bg = "sigma_blue2", fg = "sigma_green" }
"ui.popup.info" = { fg = "sigma_green", bg = "sigma_blue" }
"ui.statusline" = { fg = "sigma_green", bg = "sigma_blue2" }
"ui.statusline.inactive" = { fg = "sigma_green2", bg = "sigma_blue" }
"ui.text" = { fg = "sigma_green" }
"ui.text.focus" = { bg = "sigma_blue2", fg = "sigma_green", modifiers = ["bold"] }
"ui.window" = "sigma_green2"

[palette]
sigma_green = "#00ffc8"
sigma_green2 = "#00bb88"
sigma_blue = "#101a20"
sigma_blue2 = "#132a33"